In [1]:
print(1)

1


In [2]:
import numpy as np
print(np.__version__)

2.5.2


In [ ]:
# uv add torch torchvision
import torch

In [5]:
print(torch.__version__)
print(torch.cuda.is_available())

2.13.0+cpu
False


In [13]:
import torch
import torch.nn as nn

# 1. 실행 환경에 맞는 장치(Device) 동적 할당 (표준 패턴)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("현재 사용 장치 :", device)

# 2. 텐서 생성 시 처음부터 지정된 장치로 할당 (메모리 이동 오버헤드 방지)
x = torch.ones((2, 3), device=device)

# 3. 기존 텐서를 지정 장치로 이동
# Note: 텐서의 .to()는 원본을 변경하지 않고 '새로운 텐서'를 반환합니다.
y = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
y = y.to(device)

# 4. 신경망 모델을 지정 장치로 이동
# Note: 모델의 .to()는 모델 내부 파라미터를 'In-place(제자리)'로 이동시킵니다.
model = nn.Linear(2, 2).to(device)

# 5. 모델 연산 실행
output = model(y)
print("출력 결과 장치 :", output.device)
print(output)

현재 사용 장치 : cpu
출력 결과 장치 : cpu
tensor([[-1.6601, -0.1472],
        [-3.5034, -0.5823]], grad_fn=<AddmmBackward0>)


## 1.1 데이터로부터 직접 생성 (From Data)

In [20]:
a = torch.tensor([[1, 2], [3, 4]])
print(a)

tensor([[1, 2],
        [3, 4]])


In [25]:
# python 리스트로부터 생성
list_data = [[1, 2, 3], [4, 5, 6]]
print(f'list_data : {list_data}')
print(type(list_data)) # <class 'list'>
print()

tensor_from_list = torch.tensor(list_data, dtype=torch.float64)
print(f'List -> Tensor : {tensor_from_list}')
print(type(tensor_from_list)) # <class 'torch.Tensor'>
print(tensor_from_list.dtype)
print(tensor_from_list.device)

list_data : [[1, 2, 3], [4, 5, 6]]
<class 'list'>

List -> Tensor : tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
<class 'torch.Tensor'>
torch.float64
cpu


In [ ]:
# numpy 배열로부터 생성
np_array = np.array([10, 20, 30])
tensor_from_np = torch.tensor(np_array) # 원본 데이터와 다른 데이터를 생성한다.
print(f'tensor_from_np : {tensor_from_np}')

tensor_from_np[0] = 999
print(f'np_array : {np_array}')
print(f'tensor_from_np : {tensor_from_np}')

np_array[0] = 500
print(f'np_array : {np_array}')
print(f'tensor_from_np : {tensor_from_np}')

tensor_from_np : tensor([10, 20, 30])
np_array : [10 20 30]
tensor_from_np : tensor([999,  20,  30])
np_array : [500  20  30]
tensor_from_np : tensor([999,  20,  30])


In [ ]:
np_array = np.array([10, 20, 30])
tensor_from_np = torch.from_numpy(np_array) # 원본 데이터 메모리를 공유한다.
print(f'tensor_from_np : {tensor_from_np}')

tensor_from_np[0] = 999
print(f'np_array : {np_array}')
print(f'tensor_from_np : {tensor_from_np}')

np_array[0] = 500
print(f'np_array : {np_array}')
print(f'tensor_from_np : {tensor_from_np}')

tensor_from_np : tensor([10, 20, 30])
np_array : [999  20  30]
tensor_from_np : tensor([999,  20,  30])
np_array : [500  20  30]
tensor_from_np : tensor([500,  20,  30])


## 1.2 특정 형태(shape)와 값으로 초기화 (Structured Initialization)

In [ ]:
shape = (2, 3)
print(f'zeros :\n{torch.zeros(shape)}')
print(f'ones :\n{torch.ones(shape)}')
print(f'empty :\n{torch.empty(shape)}')
print(f'full :\n{torch.full(shape, 10)}')

print(f'arange :\n{torch.arange(10)}')          # end
print(f'arange :\n{torch.arange(0, 10)}')       # start, end
print(f'arange :\n{torch.arange(0, 10, 2)}')    # start, end, steps

print(f'linspace :\n{torch.linspace(1, 10, 5)}') # start, end, steps(등분)

zeros :
tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones :
tensor([[1., 1., 1.],
        [1., 1., 1.]])
empty :
tensor([[-1.4531e+17,  2.0753e-42,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00]])
full :
tensor([[10, 10, 10],
        [10, 10, 10]])
arange :
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arange :
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arange :
tensor([0, 2, 4, 6, 8])
linspace :
tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])


## 1.3 무작위 난수로 초기화 (Random Initialization)

In [79]:
# 난수 생성
torch.manual_seed(42)
print(f'rand :\n{torch.rand((2, 2))}') # *size
print(f'rand :\n{torch.rand(2, 2)}')

print(f'randn :\n{torch.randn(2, 2)}')
print(f'randint :\n{torch.randint(10, (2, 2))}') # high, size=()
print(f'randint :\n{torch.randint(1, 10, (2, 2))}') # high, size=()
print(f'randperm :\n{torch.randperm(10)}') # high, size=()

rand :
tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
rand :
tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])
randn :
tensor([[-1.1229, -0.1863],
        [ 2.2082, -0.6380]])
randint :
tensor([[5, 5],
        [7, 6]])
randint :
tensor([[5, 9],
        [2, 6]])
randperm :
tensor([9, 5, 7, 4, 1, 0, 6, 2, 3, 8])


## 1.4 기존 텐서의 속성을 복사하여 초기화 (_like 계열)

In [ ]:
# x = torch.tensor([[1, 2, 3], [4, 5, 6]]) # rand_like 함수 사용 시 에러 발생
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(f'x :\n{x}\n')

# shape, dtype을 그대로 복사
x_zeros = torch.zeros_like(x)
print(f'zeros_like :\n{x_zeros}')
print(f'dtype :\n{x_zeros.dtype}')
print()

x_ones = torch.ones_like(x)
print(f'ones_like :\n{x_ones}')
print(f'dtype :\n{x_ones.dtype}')
print()

x_rand = torch.rand_like(x)
print(f'rand_like :\n{x_rand}')
print(f'dtype :\n{x_rand.dtype}')
print()

# randint_like : x의 타입이 float32이므로 int 값이 아닌 원본 타입을 그대로 사용
x_randint = torch.randint_like(x, 10)
print(f'randint_like :\n{x_randint}')
print(f'dtype :\n{x_randint.dtype}')

x :
tensor([[1., 2., 3.],
        [4., 5., 6.]])

zeros_like :
tensor([[0., 0., 0.],
        [0., 0., 0.]])
dtype :
torch.float32

ones_like :
tensor([[1., 1., 1.],
        [1., 1., 1.]])
dtype :
torch.float32

rand_like :
tensor([[0.2814, 0.7886, 0.5895],
        [0.7539, 0.1952, 0.0050]])
dtype :
torch.float32

randint_like :
tensor([[9., 0., 9.],
        [6., 9., 5.]])
dtype :
torch.float32


In [ ]:
# ??

In [ ]:
# 속성을 명시하며 텐서 새성
tensor_attr = torch.ones((2, 3), dtype=torch.float16, device='cpu')
print('Shape (차원) :', tensor_attr.shape)
print('Datatype (타입) :', tensor_attr.dtype)
print('Device (장치) :', tensor_attr.device)

# 타입 변경 및 디바이스 이동
tensor_float32 = tensor_attr.to(dtype=torch.float32)
print('변경된 Datatype :', tensor_float32.dtype)

# GPU가 사용 가능한 경우 CUDA 장치로 이동
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('이동된 Device :', device)

Shape (차원) : torch.Size([2, 3])
Datatype (타입) : torch.float16
Device (장치) : cpu
변경된 Datatype : torch.float32
이동된 Device : cpu


## 2. 텐서 사이즈 (Tensor Size)

## 2.1 크기 및 차원 확인 (Size Inspection)

In [ ]:
x = torch.arange(24).reshape(2, 3, 4)
print(x)

print(x.shape)      # torch.Size([2, 3, 4])
print(x.ndim)       # 차원 수
print(x.size(0))    # 3차원일 경우 -> 1 : 공간, 2 : 행, 3 : 열
print(x.numel())    # 텐서 내부의 전체 요소 개수

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
3
2
24
